spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate.type: trace
jwt:
  secret: n9r5/Yz+iJ9bVlTpH8RZ2l4BbP7T+yRk7U/n3s5W2/P6lA5L